# Task 1: Vectorized Scaled Dot-Product Attention from Scratch


## Objective

Implement scaled dot-product attention using pure NumPy with batch-wise multi-head 4D tensors and causal masking.


## Short Theory

Attention computes softmax(QKᵀ/√dₖ)V. The causal mask prevents a token from attending to future tokens.


## Step 1: Import Libraries


In [2]:
import numpy as np
np.random.seed(60)


## Step 2: Create Batch Multi-Head Q, K and V


In [3]:
batch, heads, seq_len, d_k = 5, 8, 4, 8
Q = np.random.randn(batch, heads, seq_len, d_k)
K = np.random.randn(batch, heads, seq_len, d_k)
V = np.random.randn(batch, heads, seq_len, d_k)
print("Q:", Q.shape, "K:", K.shape, "V:", V.shape)


Q: (5, 8, 4, 8) K: (5, 8, 4, 8) V: (5, 8, 4, 8)


## Step 3: Scaled Attention Scores


In [4]:
scores = Q @ K.transpose(0, 1, 3, 2)
scores = scores / np.sqrt(d_k)
print("Scores:", scores.shape)


Scores: (5, 8, 4, 4)


## Step 4: Apply Causal Mask


In [5]:
mask = np.triu(np.ones((seq_len, seq_len), dtype=bool), k=1)
scores = np.where(mask[None, None, :, :], -1e9, scores)


## Step 5: Softmax and Attention Output


In [6]:
e = np.exp(scores - scores.max(axis=-1, keepdims=True))
weights = e / e.sum(axis=-1, keepdims=True)
output = weights @ V
print("Weights:", weights.shape)
print("Output:", output.shape)
print("Row sums:", weights.sum(axis=-1))


Weights: (5, 8, 4, 4)
Output: (5, 8, 4, 8)
Row sums: [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


## Small Experiment

Mask Check


In [7]:
print("Future-token weights:", weights[0, 0, np.triu_indices(seq_len, 1)])


Future-token weights: [[[1.         0.         0.         0.        ]
  [1.         0.         0.         0.        ]
  [1.         0.         0.         0.        ]
  [0.64247813 0.35752187 0.         0.        ]
  [0.64247813 0.35752187 0.         0.        ]
  [0.75658282 0.11203727 0.13137991 0.        ]]

 [[0.64247813 0.35752187 0.         0.        ]
  [0.75658282 0.11203727 0.13137991 0.        ]
  [0.45444422 0.4612638  0.02112927 0.06316271]
  [0.75658282 0.11203727 0.13137991 0.        ]
  [0.45444422 0.4612638  0.02112927 0.06316271]
  [0.45444422 0.4612638  0.02112927 0.06316271]]]


## Conclusion

Pure NumPy 4D scaled dot-product attention was implemented with scaling, multi-head batching, and causal masking.
